# Generated by Django 5.1.6 on 2025-04-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_package_staff_alter_package_user'),
    ]

    operations = [
    ]
