# Generated by Django 5.1.6 on 2025-04-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20250420_1849'),
    ]

    operations = [
    ]
