# Generated by Django 5.1.6 on 2025-04-21 18:07

from django.db import migrations, models
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        # Change this to the previous valid migration, e.g., '0006_previous_migration'
        ('staff', '0006_staff'),  
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
