# Generated by Django 5.1.6 on 2025-04-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_remove_feedback_updated_at_alter_feedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='feedback_entries',
            field=models.ManyToManyField(blank=True, related_name='packages', to='staff.feedback'),
        ),
    ]
