# Generated by Django 5.1.6 on 2025-04-22 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_remove_package_feedback_entries_remove_staff_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='user',
        ),
        migrations.AlterField(
            model_name='tracking',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.courier'),
        ),
    ]
