# Generated by Django 5.1.6 on 2025-04-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
