# Generated by Django 5.1.6 on 2025-04-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_staff_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.CharField(default='default_username', max_length=100),
            preserve_default=False,
        ),
    ]
